apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: control-center
  namespace: cfk
spec:
  replicas: 1
  image:
    application: {{ .Values.images.controlCenter }}
    init: {{ .Values.images.init }}
  dataVolumeCapacity: 250Mi
{{/*  tls:*/}}
{{/*    secretRef: tls-control-center*/}}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.cfk.svc.cluster.local:9071
{{/*      authentication:*/}}
{{/*        type: mtls*/}}
{{/*      tls:*/}}
{{/*        enabled: true*/}}
    schemaRegistry:
      url: https://schema-registry.cfk.svc.cluster.local:8081
{{/*      tls:*/}}
{{/*        enabled: true*/}}
