apiVersion: batch/v1
kind: Job
metadata:
  name: remove-kafkatopic-ownerrefs
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: kafkatopic-cleanup
      containers:
        - name: patch-kafkatopics
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
            topics=$(kubectl get kafkatopic -n {{ .Values.namespace }} -o jsonpath='{.items[*].metadata.name}')
              if [ -z "$topics" ]; then
                echo "No KafkaTopics found. Nothing to patch."
              else
                for topic in $topics; do
                  echo "Patching $topic..."
                  kubectl patch kafkatopic "$topic" -n {{ .Values.namespace }} \
                    --type=json \
                    -p='[{"op": "remove", "path": "/metadata/ownerReferences"}]'
                done
              fi
          env:
            - name: KUBECONFIG
              value: /root/.kube/config
      restartPolicy: Never
  backoffLimit: 1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafkatopic-cleanup
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafkatopic-cleanup-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["platform.confluent.io"]
    resources: ["kafkatopics"]
    verbs: ["get", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafkatopic-cleanup-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafkatopic-cleanup-role
subjects:
  - kind: ServiceAccount
    name: kafkatopic-cleanup
    namespace: {{ .Values.namespace }}
