{{ if .Values.restProxy.enabled }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafka-rest-proxy
  namespace: kafka-confluent-poc
spec:
  replicas: 1
  image:
    application: {{ .Values.images.restProxy }}
    init: {{ .Values.images.init }}
{{/*  license:*/}}
{{/*    secretRef: confluent-license*/}}
  podTemplate:
    labels:
      app.kubernetes.io/part-of: kafka-poc
    podSecurityContext:
      runAsUser: 1001760001
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  tls:
    secretRef: tls-group1
  authorization:
    type: rbac
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.kafka.name }}.{{ .Values.namespace }}.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credentials
      tls:
        enabled: true
    mds:
      endpoint: https://{{ .Values.kafka.name }}.{{.Values.namespace}}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: krp-mds-client
      tls:
        enabled: true
    schemaRegistry:
      url: {{ printf "http://%s.%s.svc.cluster.local:8081" .Values.schemaRegistry.name .Values.namespace}}
      tls:
        enabled: true
{{ end }}
