apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{/*  storageClass:*/}}
  {{/*    name: ocs-storagecluster-ceph-rbd*/}}
  replicas: {{ .Values.kafka.replicas }}
  image:
    application: {{ .Values.images.cpServer }}
    init: {{ .Values.images.init }}
  dataVolumeCapacity: {{ .Values.kafka.dataVolumeCapacity }}
  podTemplate:
    labels:
      app.kubernetes.io/part-of: kafka-poc
    podSecurityContext:
      runAsUser: 1001760001
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  services:
    mds:
      tls:
        enabled: false
      tokenKeyPair:
        secretRef: kafka-mds-token-keypair
      authentication:
        type: bearer
      provider:
        type: ldap
        ldap:
          address: {{ .Values.kafka.mds.ldap.url }}
          authentication:
            type: simple
            simple:
              secretRef: kafka-ldap-credential
          configurations:
            groupNameAttribute: cn
            groupObjectClass: group
            groupMemberAttribute: member
            groupMemberAttributePattern: CN=(.*),DC=ewa,DC=apg,DC=at
            groupSearchBase: dc=ewa,dc=apg,dc=at
            userNameAttribute: cn
            userMemberOfAttributePattern: CN=(.*),DC=ewa,DC=apg,DC=at
            userObjectClass: organizationalRole
            userSearchBase: dc=ewa,dc=apg,dc=at
  dependencies:
    kRaftController:
      clusterRef:
        name: kraft-poc