# https://developer.confluent.io/courses/architecture/control-plane/#kraft-cluster-node-roles
# Sounds like KRaft can either be run in dedicated or shared mode
# CfK seems to always use dedicated mode (since they are configured separately and spawn their own pods)

apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraft-poc
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kraft.replicas }}
  image:
    application: {{ .Values.images.kraftControllerApplication }}
    init: {{ .Values.images.init }}
  dataVolumeCapacity: {{ .Values.kraft.dataVolumeCapacity }}
  {{/*  license:*/}}
  {{/*    secretRef: confluent-license*/}}
podTemplate:
  labels:
    app.kubernetes.io/part-of: kafka-poc
  podSecurityContext:
    runAsUser: 1001760001
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
