{{ if .Values.controlCenter.enabled }}
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: {{ .Values.schemaRegistry.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.schemaRegistry.replicas }}
  image:
    application: {{ .Values.images.registry }}
    init: {{ .Values.images.init }}
  tls:
    secretRef: tls-group1
  authorization:
    type: rbac
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.kafka.name }}.{{.Values.namespace}}.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credentials
      tls:
        enabled: true
    mds:
      endpoint: https://{{ .Values.kafka.name }}.{{.Values.namespace}}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: sr-mds-client
      tls:
        enabled: true
{{ end }}