images:
  kraftControllerApplication: docker.io/confluentinc/cp-server:7.5.0
  cpServer: confluentinc/cp-server:7.5.0
  registry: confluentinc/cp-schema-registry:7.5.0
  controlCenter: confluentinc/cp-enterprise-control-center:7.5.0
  init: confluentinc/confluent-init-container:2.7.0
